### ISSUE TITLE
Baud rate ignored in .77+

### ISSUE THREAD

**Issue by martykazmaier** [mkrueger/icy_tools#27] opened 2024-08-24 06:05 UTC
At shsbbs.net at least, with a secure websocket connection, the terminal baud rate emulation is ignored.  I'd like to be able to see my scrolling ansis!

**Comment by dream7prod** [comment] 2024-08-26 17:57
Same here, baud rate ignored on iCY TERM, via local telnet connection and everything else...
tested on 0.7.7 and 0.7.8

Thank you

**Comment by mkrueger** [comment] 2024-12-22 08:19
Duplicate of #25.

**Closed by mkrueger** 2024-12-22 08:19 UTC
